#First draft of the CI file 
#Using runner 350 shell runner as shared runner

stages:
  - build
  - deploy

build-job:
  tags:
    #- ssh
    - runner350
    
  stage: build
  script:
    #Changing directory to root
    - ./gradlew build  #Ask about the commands that need to go before build

  only:
    - master
  artifacts:
    paths:
      - ~/      #path to root
      - ~/gradle/wrapper  #path to .jar file
deploy-job:
  tags:
    #- ssh
    - runner350
  stage: deploy
  script:
    - eval $(ssh-agent -s)  #set up SSH for CI 
    - ssh-add <(echo "$RSYNC_KEY")
    - rsync -auvz -e "ssh" build/reports/tests/ aholm@atria.cs.odu.edu:GitLab1/