#First draft of the CI file 
#Using runner 350 shell runner as shared runner

stages:
  - build
  - deploy

build-job:
  tags:
    #- ssh
    - runner350
    
  stage: build
  script:
    #Changing directory to root
    - ls -l
    - cd /home/gitlab-runner/builds/5dc73e18/0/mpark/Red2
    - ./gradlew build  #change directory to root then build file
    - ./gradlew javadoc
    - ./gradlew collectStats
  only:
    - master
  artifacts:
    paths:
      - /home/gitlab-runner/builds/5dc73e18/0/mpark/Red2   #path to root
      - /home/gitlab-runner/builds/5dc73e18/0/mpark/Red2/gradle/wrapper  #path to .jar file

deploy-job:
  tags:
    #- ssh
    - runner350
  stage: deploy
  script:
    - eval $(ssh-agent -s)  #set up SSH for CI 
    - ssh-add <(echo "$RSYNC_T")
    - rsync -auvz -e "ssh" build/reports/tests/test/ mpark@atria.cs.odu.edu:/home/mpark/public_html/cs350/reports
    - rsync -auvz -e "ssh" build/docs/javadoc/ mpark@atria.cs.odu.edu:/home/mpark/public_html/cs350/javadoc
    - rsync -auvz -e "ssh" build/reports/ mpark@atria.cs.odu.edu:/home/mpark/public_html/cs350/analysis
    

