#First draft of the CI file 
#Using runner 350 shell runner as shared runner

stages:
  - build
  - deploy


build-job:
  tags:
    5dc73e18
    
  stage: build
  script:
    ./gradlew build  #Ask about the commands that need to go before build
    
    - # script line 2
    - # ...
  only:
    - master